### ISSUE TITLE
Melhorar forma de criar tópicos

### ISSUE THREAD

**Issue by reebr** [reebr/pynvite#2]
Existe o [método para criar novos tópicos][1], porém ele foi criado se baseando em URL. Por exemplo, supondo que o queira criar um tópico no fórum "Novidades", seria necessário algo semelhante a isto:

```python
from platforms.xenforo import Xenforo

# Nome que o fórum aparece na URL, isso está muito ruim!!!
forum= 'novidades.346'

xenforo = Xenforo('http://www.forumteste.com.br')

if xenforo.login('meuUsuarioX', 'minhaSenhaY'):
    xenforo.post_thread(forum, 'Título', 'Conteúdo do tópico.')
```

Isso enviaria uma requisição para `http://www.forumteste.com.br/forums/novidades.346/add-thread`.

O problema é esse nome do fórum na URL: `novidades.346` Acredito que exista uma forma mais simples de referenciar o fórum onde deve ser criado o tópico, algum ID, etc. 

- [x] Fazer uma análise dos parâmetros enviados na requisição via browser (usando alguma extensão, e.g [HTTP Live Headers][2]), procurar possíveis alternativas.
- [x] Melhorar a forma que o método recebe a origem de onde o tópico deve ser criado.
- [x] Analisar se o texto que antecede o número na URL é irrelevante na requisição, isto é, pode ser qualquer coisa, e.g `x.346`. Verificar se uma chamada à `http://www.forumteste.com.br/forums/xxx.346/add-thread` ou `http://www.forumteste.com.br/forums/346/add-thread` criará o tópico corretamente.

[1]:https://github.com/reebr/pynvite/blob/master/platforms/xenforo.py#L49-L64
[2]:https://addons.mozilla.org/pt-br/firefox/addon/live-http-headers/

**Comment by pauloabreu** [comment]
Eu testei tanto para comentar quanto para criar thread, O texto que antecede o Id é irrelevante na requisição como já tinha falado antes, deve se mandar o requisição ex: **http://www.forumteste.com.br/forums/346/add-thread**
